<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net50</TargetFrameworks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

 <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.3" />
  </ItemGroup>

</Project>
