<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net50</TargetFrameworks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

 <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetAppDir>$(MSBuildProjectDirectory)/../../bin</TargetAppDir>
  </PropertyGroup>

  <ItemGroup>
    <CompiledResult Include="$(TargetDir)/*.*" />
  </ItemGroup>

  <Target Name="CopyLastBuild" AfterTargets="AfterBuild" Condition="$(TargetFramework) == 'net50'">
    <Copy SourceFiles="@(CompiledResult)" DestinationFolder="$(TargetAppDir)" />
</Target>

</Project>
