<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
   <OutputType>Exe</OutputType>
    <TargetFramework>net80</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../output/docgen2.output.csproj" />
    <ProjectReference Include="../parser/docgen2.parser.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetAppDir>$(MSBuildProjectDirectory)/../../bin</TargetAppDir>
  </PropertyGroup>

  <ItemGroup>
    <CompiledResult Include="$(TargetDir)/*.*" />
  </ItemGroup>

  <Target Name="CopyLastBuild" AfterTargets="AfterBuild" Condition="$(TargetFramework) == 'net50'">
    <Copy SourceFiles="@(CompiledResult)" DestinationFolder="$(TargetAppDir)" />
</Target>
</Project>
