<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net46;netstandard2.0</TargetFrameworks>
    <BuildOutputTargetFolder>tasks</BuildOutputTargetFolder>
  </PropertyGroup>

<ItemGroup>
    <Compile Remove="test\**" />
    <EmbeddedResource Remove="test\**" />
    <None Remove="test\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="build\Gehtsoft.Build.DocGen.props" PackagePath="build\" />
    <Content Include="buildMultiTargeting\Gehtsoft.Build.DocGen.props" PackagePath="buildMultiTargeting\" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">
    <Reference Include="System.IO.Compression" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Framework">
      <Version>15.1.1012</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Build.Utilities.Core">
      <Version>15.1.1012</Version>
    </PackageReference>
    <ProjectReference Include="..\output\docgen2.output.csproj" />
    <ProjectReference Include="..\parser\docgen2.parser.csproj" />
    <PackageReference Update="@(PackageReference)" PrivateAssets="All" />
  </ItemGroup>
</Project>
